# Generated by Django 3.0.4 on 2020-11-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="date_added",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="date_last_modified",
            field=models.DateField(auto_now=True),
        ),
    ]
