# Generated by Django 3.0.4 on 2021-01-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_profile_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
    ]
