# Generated by Django 3.0.4 on 2021-01-20 21:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_profile_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="id",
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_id",
            field=models.UUIDField(
                default=uuid.UUID("f362f335-a376-4656-91b0-230eba69d823"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
