# Generated by Django 3.0.4 on 2021-01-20 21:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_auto_20210120_2136"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="slug",
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_id",
            field=models.UUIDField(
                default=uuid.UUID("ea50d395-6ff0-4984-ac2e-da0e41aab406"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
