# Generated by Django 3.0.4 on 2021-01-20 21:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_auto_20210120_2139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_id",
            field=models.UUIDField(
                default=uuid.UUID("8df858f9-4226-4c10-9c46-0e5239261131"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
