# Generated by Django 3.0.4 on 2021-01-20 22:21

from django.db import migrations, models
import django_resized.forms
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_auto_20210120_2143"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=75,
                size=[480, 350],
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_id",
            field=models.UUIDField(
                default=uuid.UUID("3626a08a-d5df-4173-b34e-e8b2cb0fb871"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
