# Generated by Django 3.0.4 on 2021-01-22 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_auto_20210120_2221"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_id",
            field=models.UUIDField(
                default=uuid.UUID("b11e34dc-3f43-485f-b45a-8ccb21659d1f"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
