# Generated by Django 3.0.4 on 2021-01-25 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0010_auto_20210122_1923"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="follower",
            managers=[
                ("follower_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_id",
            field=models.UUIDField(
                default=uuid.UUID("6e449166-f0ef-4033-abdd-6f2efd503e32"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="follower",
            unique_together={("user", "follower")},
        ),
    ]
