# Generated by Django 3.0.4 on 2021-01-25 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_auto_20210125_1214"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="follower",
            managers=[],
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_id",
            field=models.UUIDField(
                default=uuid.UUID("b252c61f-0a51-4cf8-8905-31a386f5a6f5"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
