# Generated by Django 3.0.4 on 2021-03-22 18:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_auto_20210125_1443"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_id",
            field=models.UUIDField(
                default=uuid.UUID("16ced218-edde-4c9e-b7c0-d8946f3a3c4e"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
