# Generated by Django 3.0.4 on 2021-03-25 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_auto_20210322_1836"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_id",
            field=models.UUIDField(
                default=uuid.UUID("5417a548-b7fd-4901-bbfa-3089afe6eb3d"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
