# Generated by Django 3.0.4 on 2021-03-25 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_auto_20210325_1341"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_id",
            field=models.UUIDField(
                default=uuid.UUID("0b6c3a4b-4bdd-47a6-9fa0-275a37eacaa1"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
