# Generated by Django 3.0.4 on 2020-11-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
