# Generated by Django 3.0.4 on 2021-01-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_social"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpeningTime",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ],
                        unique=True,
                    ),
                ),
                ("from_hour", models.TimeField()),
                ("to_hour", models.TimeField()),
            ],
            options={
                "verbose_name": "OpeningTime",
            },
        ),
    ]
