# Generated by Django 3.0.4 on 2020-11-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_auto_20201127_1746"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("additional_description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Ratings",
            },
        ),
    ]
