# Generated by Django 3.0.4 on 2020-12-19 12:58

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_guest_musicgenre_venue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="country",
        ),
        migrations.AlterField(
            model_name="city",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.State"
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.DeleteModel(
            name="Country",
        ),
    ]
