# Generated by Django 3.0.4 on 2020-12-19 14:29

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("common", "0006_auto_20201219_1347"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="address",
        ),
        migrations.AlterField(
            model_name="address",
            name="location",
            field=address.models.AddressField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="address.Address",
            ),
        ),
    ]
