# Generated by Django 3.0.4 on 2020-12-19 14:39

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("common", "0007_auto_20201219_1429"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="location",
            field=address.models.AddressField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="address.Address",
            ),
            preserve_default=False,
        ),
    ]
