# Generated by Django 3.0.4 on 2020-12-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_auto_20201219_1439"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="city",
        ),
        migrations.RemoveField(
            model_name="address",
            name="state",
        ),
    ]
