# Generated by Django 3.0.4 on 2020-12-19 16:34

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_auto_20201219_1634"),
        ("address", "0003_auto_20200830_1851"),
        ("account", "0004_auto_20201219_1634"),
        ("common", "0009_auto_20201219_1619"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="address",
            field=address.models.AddressField(
                on_delete=django.db.models.deletion.CASCADE, to="address.Address"
            ),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
