# Generated by Django 3.0.4 on 2020-12-19 17:01

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("common", "0010_auto_20201219_1634"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="state",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="guest",
            name="country",
        ),
        migrations.AddField(
            model_name="guest",
            name="address",
            field=address.models.AddressField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="address.Address",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="City",
        ),
        migrations.DeleteModel(
            name="State",
        ),
    ]
