# Generated by Django 3.0.4 on 2020-12-19 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                ("is_special", models.BooleanField(default=False)),
                ("code", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="business.Business",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Offers",
                "unique_together": {("business", "title")},
            },
        ),
    ]
