# Generated by Django 3.0.4 on 2021-01-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="slug",
            field=models.SlugField(
                default=1,
                help_text="Unique value for product page URL, created from name.",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
