# Generated by Django 3.0.4 on 2020-12-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0002_auto_20201219_1404"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="limit",
            field=models.IntegerField(default=0),
        ),
    ]
