# Generated by Django 3.0.4 on 2020-12-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("club", "0010_auto_20201205_1315"),
        ("common", "0004_guest_musicgenre_venue"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("priority_level", models.IntegerField(default=0)),
                (
                    "genre",
                    models.ManyToManyField(
                        related_name="music", to="common.MusicGenre"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndependentEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("to_be_held", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.Event"
                    ),
                ),
                (
                    "guest",
                    models.ManyToManyField(
                        blank=True, related_name="independent_guest", to="common.Guest"
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="common.Venue"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClubEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("to_be_held", models.DateTimeField(blank=True, null=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="club.Club"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.Event"
                    ),
                ),
                (
                    "guest",
                    models.ManyToManyField(
                        blank=True, related_name="guest", to="common.Guest"
                    ),
                ),
            ],
        ),
    ]
