# Generated by Django 3.0.4 on 2020-12-05 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventsetup",
            options={"verbose_name_plural": "Event SetUp"},
        ),
    ]
