# Generated by Django 3.0.4 on 2021-01-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
