# Generated by Django 3.0.4 on 2021-01-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_event_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(
                default=1,
                help_text="Unique value for product page URL, created from name.",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
