# Generated by Django 3.0.4 on 2021-01-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_auto_20210108_1222"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
