# Generated by Django 3.0.4 on 2021-01-10 15:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_event_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
