# Generated by Django 3.0.4 on 2021-01-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0007_eventsocial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="new_price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name="event",
            name="old_price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
