# Generated by Django 3.0.4 on 2021-01-10 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0009_eventimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventimage",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="event.Event"
            ),
        ),
    ]
