# Generated by Django 3.0.4 on 2021-01-10 17:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0011_eventservicerating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+254720323306", max_length=128, region=None
            ),
            preserve_default=False,
        ),
    ]
