# Generated by Django 3.0.4 on 2020-12-25 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0015_reviewattribute_rating"),
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.ReviewAttribute"
            ),
        ),
    ]
