# Generated by Django 3.0.4 on 2020-12-25 21:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("business", "0004_auto_20201219_1701"),
        ("review", "0002_auto_20201225_2055"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("business", "user")},
        ),
    ]
