# Generated by Django 3.0.4 on 2021-03-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_businessservicerating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="images",
            new_name="image_1",
        ),
        migrations.RemoveField(
            model_name="review",
            name="ratings",
        ),
        migrations.AddField(
            model_name="review",
            name="image_2",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="review",
            name="image_3",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="review",
            name="experience",
            field=models.CharField(max_length=200),
        ),
    ]
