# Generated by Django 3.0.4 on 2021-03-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_auto_20210325_1341"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
