# Generated by Django 3.0.4 on 2020-12-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_auto_20201225_2100"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=1),
        ),
    ]
