# Generated by Django 3.0.4 on 2021-03-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_auto_20210325_1415"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
    ]
