# Generated by Django 3.0.4 on 2020-12-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_auto_20201228_1224"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="rating",
        ),
    ]
