# Generated by Django 3.0.4 on 2020-12-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0005_remove_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="ratings",
            field=models.IntegerField(default=1),
        ),
    ]
