# Generated by Django 3.0.4 on 2020-12-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0006_review_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="moderated",
            field=models.BooleanField(default=False),
        ),
    ]
