# Generated by Django 3.0.4 on 2021-01-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_auto_20210107_1849"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
