# Generated by Django 3.0.4 on 2020-12-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_auto_20201219_1634"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={"verbose_name_plural": "Businesses"},
        ),
    ]
