# Generated by Django 3.0.4 on 2021-01-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_business_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Unique value for product page URL, created from name.",
                max_length=255,
                null=True,
            ),
        ),
    ]
