# Generated by Django 3.0.4 on 2021-01-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0006_business_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="icon",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
