# Generated by Django 3.0.4 on 2021-01-08 20:45

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0007_service_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_last_modified", models.DateField(auto_now=True)),
                ("date_added", models.DateField(auto_now=True)),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        quality=75,
                        size=[120, 120],
                        upload_to="",
                    ),
                ),
                (
                    "img_category",
                    models.CharField(
                        choices=[("thumbnail", "thumbnail"), ("other", "other")],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="business.Business",
                    ),
                ),
            ],
            options={
                "db_table": "business_images",
            },
        ),
    ]
