# Generated by Django 3.0.4 on 2021-01-08 21:11

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0009_auto_20210108_2056"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessimage",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format=None,
                keep_meta=True,
                quality=75,
                size=[480, 350],
                upload_to="",
            ),
        ),
    ]
