# Generated by Django 3.0.4 on 2021-01-25 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0012_business_openning_times"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesssocial",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social",
                to="business.Business",
            ),
        ),
    ]
