# Generated by Django 3.0.4 on 2021-03-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0014_businessservicerating_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BusinessServiceRating",
        ),
    ]
