# Generated by Django 3.0.4 on 2021-03-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0015_delete_businessservicerating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
