# Generated by Django 3.0.4 on 2021-03-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0016_auto_20210325_2222"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="rating",
        ),
    ]
