# Generated by Django 3.0.4 on 2020-11-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="date_added",
            field=models.DateField(auto_now=True),
        ),
    ]
