# Generated by Django 3.0.4 on 2020-11-27 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_rating"),
        ("club", "0003_club_date_last_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="rating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="common.Rating",
            ),
        ),
    ]
