# Generated by Django 3.0.4 on 2020-11-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0004_club_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="club",
            old_name="price",
            new_name="price_type",
        ),
    ]
