# Generated by Django 3.0.4 on 2020-12-04 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0006_visitorcount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trending",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_last_modified", models.DateField(auto_now=True)),
                ("date_added", models.DateField(auto_now=True)),
                ("thumbs_up_count", models.IntegerField(default=0)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="club.Club"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
