# Generated by Django 3.0.4 on 2020-12-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0008_auto_20201204_1158"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="guest",
            field=models.ManyToManyField(
                blank=True, related_name="guest", to="club.Guest"
            ),
        ),
    ]
