# Generated by Django 3.0.4 on 2020-12-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0009_auto_20201204_1158"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="event",
            name="guest",
        ),
        migrations.RemoveField(
            model_name="independentevent",
            name="address",
        ),
        migrations.RemoveField(
            model_name="independentevent",
            name="event",
        ),
        migrations.DeleteModel(
            name="ClubEvent",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="Guest",
        ),
        migrations.DeleteModel(
            name="IndependentEvent",
        ),
        migrations.DeleteModel(
            name="MusicGenre",
        ),
    ]
